// <auto-generated />
using System;
using DubizzleScraper.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DubizzleScraper.Data.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("DubizzleScraper.Models.Property", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd()
                .HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

            b.Property<decimal?>("AreaSqm").HasColumnType("decimal(10,2)");
            b.Property<int?>("Bathrooms").HasColumnType("int");
            b.Property<int?>("Bedrooms").HasColumnType("int");
            b.Property<string>("Description").HasMaxLength(2000).HasColumnType("nvarchar(2000)");
            b.Property<string>("District").HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<string>("DubizzleId").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<string>("Governorate").HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<string>("ImageUrl").HasMaxLength(1000).HasColumnType("nvarchar(1000)");
            b.Property<bool>("IsActive").HasColumnType("bit");
            b.Property<string>("Location").HasMaxLength(200).HasColumnType("nvarchar(200)");
            b.Property<bool>("NotificationSent").HasColumnType("bit");
            b.Property<DateTime?>("PostedAt").HasColumnType("datetime2");
            b.Property<decimal?>("Price").HasColumnType("decimal(18,2)");
            b.Property<string>("PricePeriod").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<DateTime>("ScrapedAt").HasColumnType("datetime2");
            b.Property<string>("SellerName").HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<string>("SellerPhone").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<string>("SellerType").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<string>("Title").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
            b.Property<int>("Type").HasColumnType("int");
            b.Property<string>("Url").HasMaxLength(1000).HasColumnType("nvarchar(1000)");

            b.HasKey("Id");
            b.HasIndex("DubizzleId").IsUnique();
            b.HasIndex("NotificationSent");
            b.HasIndex("ScrapedAt");
            b.ToTable("Properties");
        });

        modelBuilder.Entity("DubizzleScraper.Models.SearchFilter", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
            b.Property<string>("District").HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<string>("Governorate").HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<bool>("IsActive").HasColumnType("bit");
            b.Property<string>("Keywords").HasMaxLength(200).HasColumnType("nvarchar(200)");
            b.Property<int?>("MaxBedrooms").HasColumnType("int");
            b.Property<decimal?>("MaxArea").HasColumnType("decimal(18,2)");
            b.Property<decimal?>("MaxPrice").HasColumnType("decimal(18,2)");
            b.Property<int?>("MinBedrooms").HasColumnType("int");
            b.Property<decimal?>("MinArea").HasColumnType("decimal(18,2)");
            b.Property<decimal?>("MinPrice").HasColumnType("decimal(18,2)");
            b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<int>("PropertyType").HasColumnType("int");

            b.HasKey("Id");
            b.ToTable("SearchFilters");

            b.HasData(
                new { Id = 1, Name = "شقق إيجار القاهرة", PropertyType = 0, Governorate = "cairo",
                      IsActive = true, CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) },
                new { Id = 2, Name = "شقق بيع القاهرة", PropertyType = 1, Governorate = "cairo",
                      IsActive = true, CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc) }
            );
        });
#pragma warning restore 612, 618
    }
}
